### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by Juuxel** [tyra314/Inca#1]
Crochet and Cotton aren't declared as requirements in the `requires` block of Inca's `fabric.mod.json`, so the game will crash with random `ClassNotFoundException`s and `NoClassDefFoundError`s instead of proper missing dependency exceptions.

**Comment by tyra314** [comment]
Fixed in 36033d749192d5da1930ee903c8cdc81d5e42dac

**Comment by Juuxel** [comment]
That was quick. Thanks!
