### ISSUE TITLE
Crochet is abandoned, please depend on another library

### ISSUE THREAD

**Issue by calloatti** [tyra314/Inca#5]
Crochet is abandoned and it crashes on 1.14.4 unless patched, could you use another library please.

Edit: Just use the Fabric API I guess.

**Comment by tyra314** [comment]
![](https://i.kym-cdn.com/entries/icons/original/000/002/830/sad_frog.jpg)

I'll replace it.

**Comment by tyra314** [comment]
Fixed in 1.0.6
